[package]
name = "paho-mqtt-sys"
version = "0.2.0"
authors = ["Frank Pagliughi <fpagliughi@mindspring.com>"]
package = "build.rs"
description = """
Rust wrapper for the Paho MQTT C Client Library.
"""

[features]
#default = ["paho_mqtt_1_2_1"]
#default = []
buildtime_bindgen = ["bindgen"]
bundled = ["cmake"]

[build-dependencies]
bindgen = { version = "0.42", optional = true }
cmake = { version = "0.1", optional = true }


