[package]
name = "paho-mqtt"
version = "0.4.0"
authors = ["Frank Pagliughi <fpagliughi@mindspring.com>"]
homepage = "https://github.com/eclipse/paho.mqtt.rust"
repository = "https://github.com/eclipse/paho.mqtt.rust"
keywords = [ "MQTT", "IoT", "Paho", "messaging" ]
readme = "README.md"
description = """
The Eclipse Paho MQTT Rust Client Library
This is currently a wrapper around the Paho C library.
"""

[dependencies]
paho-mqtt-sys = { path = "paho-mqtt-sys", default-features=false }
libc = "0.2"
log = "0.3"
env_logger = "0.3"

[features]
default = ["bundled", "ssl"]
bundled = ["paho-mqtt-sys/bundled"]
build_bindgen = ["paho-mqtt-sys/build_bindgen"]
ssl = ["paho-mqtt-sys/ssl"]

